### ISSUE TITLE
Execution succeeds, however nothing is saved to disk

### ISSUE THREAD

**Issue by aidenmitchell** [skyme5/snapchat-dl#12]
* Snapchat Downloader version: 1.4.3
* Python version: 3.9.9
* Operating System: Windows 10 x64

### Description
Attempting to download stories succeeds, however no media is saved to disk. The folder is empty.

### What I Did

```
snapchat-dl.exe -P C:\Users\aiden.admin\Downloads\media\snapstories\ username
2021-12-22 17:33:17.627 | INFO     | snapchat_dl.snapchat_dl:download:104 - [+] username has 4 stories
2021-12-22 17:33:17.629 | INFO     | snapchat_dl.snapchat_dl:download:135 - [✔] username stories downloaded
```

**Comment by skyme5** [comment]
It's working fine, files should be downloaded successfully. Can you check for other usernames?

**Comment by aidenmitchell** [comment]
So looking at the .json file, the actual link to the media is missing. I tried downloading with another Python utility, and it reported the same thing, “Media present, but no link returned.” I assume this is a Snapchat issue, and not a downloader issue.

**Comment by skyme5** [comment]
Closing, given the above.
