### ISSUE TITLE
Doesn't work, it hangs up

### ISSUE THREAD

**Issue by UnixCro** [skyme5/snapchat-dl#7]
When I give the link, I write snapchat-dl “https://story.snapchat.com/s/ story I want.  

In the output it says that this following user has, for example, 10 stories.  After that no more happens.  Neither the program reports nor the terminal aborts the process.  Also the option with "-c".  It says there that this user suddenly has no more stories ?!  

I also had difficulty finding the program after "pip3 install snapchat-dl", because it was not in / usr / local / bin but in /Library/Frameworks/Python.framework/Versions/3.6/bin/snapchat-dl.  

Even if it has a few bugs it is still a great program, especially because I don't have to keep entering python3 snapchat-dl, but it runs as cleanly as "youtube-dl". The parameters are also kept very nice.  

Do you think it is also possible to download the story from private people by logging into your account?

**Comment by skyme5** [comment]
- Currently single story download is not implemented, you need to supply username to download available stories. (e.g. `snapchat-dl <username>`)
- Use `--user` flag on unix to install the package
- `-c` options scans clipboard for valid username and attempts to download stories

**Comment by UnixCro** [comment]
Now I see that it really works with usernames. Apparently it doesn't support a single story yet, unfortunately I wasn't aware of that.

Thank you for your helpful answer.
Hope you will add private story downloading later, I would definitely assist you. Unfortunately, that should be very difficult

**Comment by UnixCro** [comment]
Hello it's me again.  I didn't want to create another problem.  It's been almost a year now and I love snapchat-dl and use it every day.  But I need support for private accounts.  Please insert that in the code and as a thank you I'll send you $ 10 in BTC.  Greetings and stay healthy

**Comment by skyme5** [comment]
@UnixCro Thank you for using snapchat-dl, currently, exploring Snapchat's private API would require a considerable amount of time and effort. Will keep you posted on any progress related to this.
