### ISSUE TITLE
Downloads invalid media files

### ISSUE THREAD

**Issue by ahsaassy** [skyme5/snapchat-dl#9]
* Snapchat Downloader version: 1.2.1
* Python version: 3.9.6
* Operating System: Android 10 (Termux)

### Description

Sometimes stories get downloaded but they're not valid media files. Account is public.

### What I Did

```
snapchat-dl -s -j 1 --sleep-interval 10
```
This is how they look like in gallery, you can't view them: https://i.imgur.com/8qapHpN.jpg
Here's the files: mega.nz/ 2cBilLTB#7mdH3Y2KSYHCp6lfC_akPg

**Comment by skyme5** [comment]
I think the downloaded files have `webp` format which is not supported in windows explorer. Can you try viewing them in a browser?

**Comment by ahsaassy** [comment]
The files are not in webp, bro. I've tried opening them in different apps and even Chrome. Also tried changing extension, encoding them to jpg,  it just won't work.
